// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmBoZFwkKgpAC8IK5Y2LpVJmsCTNQhz6c',
    appId: '1:1022087831237:web:7d7c0d26f807765cec9aac',
    messagingSenderId: '1022087831237',
    projectId: 'my-ecommerce-app-03062004',
    authDomain: 'my-ecommerce-app-03062004.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-03062004.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNulr649pYpu0IsJjECnGcp3H6lRZKkE',
    appId: '1:1022087831237:android:cb31ec70ea80190fec9aac',
    messagingSenderId: '1022087831237',
    projectId: 'my-ecommerce-app-03062004',
    storageBucket: 'my-ecommerce-app-03062004.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhtr-PGfV38tPkqTF05UeUtx7RlBOqnJU',
    appId: '1:275688423981:web:316aed1252a55a661d6ea4',
    messagingSenderId: '275688423981',
    projectId: 'my-ecommerce-app-093006',
    authDomain: 'my-ecommerce-app-093006.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-093006.firebasestorage.app',
  );

}